{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: shlink-shlinkchart-ui
  labels: {{- include "shlinkchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: shlink-shlinkchart-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port | default 8081 }}
      targetPort: {{ .Values.ui.service.targetPort | default 8080 }}
{{- end }}
